# Generated by Django 3.0.6 on 2020-09-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0027_trigger_update_full_account_codes_effective'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementline',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statementline',
            name='z4mp',
            field=models.TextField(blank=True, default=''),
        ),
    ]
