# Generated by Django 3.0.6 on 2020-09-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0028_auto_20200929_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementline',
            old_name='z4mp',
            new_name='z4no',
        ),
    ]
